export const gamesData = [
    {
        id: 1,
        title: "Elden Ring",
        imageUrl: "https://i.ibb.co/GTd8zS1/Elden-Ring.png",
        company: "Bandai Namco",
        type: "PS5",
        price: 69.99,
        genre: "RPG",
    },
    {
        id: 2,
        title: "Marvel's Spider-Man:Miles Morales",
        imageUrl: "https://i.ibb.co/ypK7yYJ/Spider-Men.png",
        company: "Sony Interactive",
        type: "PS5",
        price: 49.99,
        genre: "Action",
    },
    {
        id: 3,
        title: "Resident Evil Village",
        imageUrl: "https://i.ibb.co/mJ0Gpwy/RE-village.png",
        company: "Capcom",
        type: "PS4",
        price: 69.99,
        genre: "Survival",
    },
    {
        id: 4,
        title: "Ghost of Tsusushima",
        imageUrl: "https://i.ibb.co/yPnKMLk/Ghost-of-Tsusushima.png",
        company: "Sucker Punch",
        type: "PS4",
        price: 69.99,
        genre: "RPG",
    },
    {
        id: 5,
        title: "FIFA 22",
        imageUrl: "https://i.ibb.co/2vhMpNr/Fifa-22.png",
        company: "EA",
        type: "PS5",
        price: 79.99,
        genre: "Sport",
    },  
    {
        id: 6,
        title: "Hoirzon Forbidden West",
        imageUrl: "https://i.ibb.co/rGnSxvh/Horizon.png",
        company: "Sony Interactive",
        type: "PS4",
        price: 89.99,
        genre: "RPG",
    },
    {
        id: 7,
        title: "Dying Light 2",
        imageUrl: "https://i.ibb.co/x30XTtV/Dying-Light.png",
        company: "Techland",
        type: "PS4",
        price: 59.99,
        genre: "Survival",
    },
    {
        id: 8,
        title: "Star Wars Jedi:Fallen Order",
        imageUrl: "https://i.ibb.co/2NcFSj5/Star-Wars.png",
        company: "Respawn",
        type: "PS4",
        price: 19.99,
        genre: "Action",
    },
    {
        id: 9,
        title: "Sifu",
        imageUrl: "https://i.ibb.co/T47hNy6/Sifu.png",
        company: "Sloclap",
        type: "PS5",
        price: 49.99,
        genre: "Action",
    },
    {
        id: 10,
        title: "Gran Turismo 7",
        imageUrl: "https://i.ibb.co/JRVK4k7/Gran.png",
        company: "Sony Interactive",
        type: "PS5",
        price: 79.99,
        genre: "Sport",
    },
    {
        id: 11,
        title: "Call of Duty: Vanguard",
        imageUrl: "https://i.ibb.co/b1d0g6z/COD.png",
        company: "Activision",
        type: "PS4",
        price: 79.99,
        genre: "Shooting",
    },
    {
        id: 12,
        title: "Riders Republic",
        imageUrl: "https://i.ibb.co/pyMYhCp/Riders.png",
        company: "Ubisoft",
        type: "PS4",
        price: 39.99,
        genre: "Sport",
    },
    {
        id: 13,
        title: "Cyberpunk 2077",
        imageUrl: "https://i.ibb.co/Dzt4TfK/Cyberpunk-2077.png",
        company: "CD Projekt",
        type: "PS4",
        price: 59.99,
        genre: "RPG",
    },
    {
        id: 14,
        title: "Hitman 3",
        imageUrl: "https://i.ibb.co/b36kw5c/Hitman.png",
        company: "IO interactive",
        type: "PS4",
        price: 59.99,
        genre: "Action",
    },
    {
        id: 15,
        title: "FIFA 21",
        imageUrl: "https://i.ibb.co/Jz82sSQ/Fifa-21.png", 
        company: "EA",
        type: "PS4",
        price: 49.99,
        genre: "Sport",
    },
    {
        id: 16,
        title: "Watch Dogs Legion",
        imageUrl: "https://i.ibb.co/K5PmGVT/Watch-Dogs-Legion.png", 
        company: "Ubisoft",
        type: "PS4",
        price: 59.99,
        genre: "Adventure",
    },
    {
        id: 17,
        title: "Cloudpunk",
        imageUrl: "https://i.ibb.co/Sv54fbB/Cloudpunk.png", 
        company: "Male Whispering",
        type: "PS4",
        price: 19.99,
        genre: "Adventure",
    },
    {
        id: 18,
        title: "Crysis Remastered",
        imageUrl: "https://i.ibb.co/rHFVWkC/Crysis-Remastered.png", 
        company: "Crytek",
        type: "PS4",
        price: 29.99,
        genre: "Shooting",
    },
    {
        id: 19,
        title: "Far Cry 6",
        imageUrl: "https://i.ibb.co/3WHvcV7/Far-Cry-6.png",
        company: "Ubisoft",
        type: "PS5",
        price: 59.99,
        genre: "Shooting",
    },
    {
        id: 20,
        title: "NBA 2k21",
        imageUrl: "https://i.ibb.co/zSP9rjm/NBA.png",
        company: "2K Sports",
        type: "PS4",
        price: 59.99,
        genre: "Sport",
    },
    {
        id: 21,
        title: "Death Stranding",
        imageUrl: "https://i.ibb.co/Rhp7HgL/DS.png",
        company: "Kojima",
        type: "PS4",
        price: 39.99,
        genre: "Action",
    },
    {
        id: 22,
        title: "Days Gone",
        imageUrl: "https://i.ibb.co/BrfjzsH/DG.png",
        company: "Sony Interactive",
        type: "PS4",
        price: 39.99,
        genre: "Adventure",
    },
    {
        id: 23,
        title: "Diablo 3:Eternal Collections",
        imageUrl: "https://i.ibb.co/LQfB0tM/Diablo-3.png",
        company: "Blizzard",
        type: "PS4",
        price: 49.99,
        genre: "RPG",
    },
    {
        id: 24,
        title: "Mortal Shell",
        imageUrl: "https://i.ibb.co/F7GQyrF/Mortal-Shell.png",
        company: "Playstack",
        type: "PS4",
        price: 25.49,
        genre: "RPG",
    },
    {
        id: 25,
        title: "DOOM Eternal",
        imageUrl: "https://i.ibb.co/QXx7TQ2/DOOM-Eternal.png",
        company: "Bethesda",
        type: "PS4",
        price: 29.99,
        genre: "Shooting",
    },
    {
        id: 26,
        title: "The Witcher 3: Wild Hunt",
        imageUrl: "https://i.ibb.co/9gjWSGF/The-Witcher-3.png",
        company: "CD projekt Red",
        type: "PS4",
        price: 49.99,
        genre: "RPG",
    },
]